[default]

TEST_ONLY = true
TEST_LR_RANGE = false

SEED = 42
USE_AMP = true
LR = 3e-5
LR_WARMUP_STEP = 500
LR_COSINE_T_0 = 500
LR_COSINE_T_MULT = 1
NUM_T = 25
USE_NUM_T = true
USE_MULTISTEP = false

NUM_EPOCHS = 50
NUM_WORKERS = 8
BATCH_SIZE_PER_GPU = 8
ACCUM_STEP = 32

# LOG_EVERY_STEP = 50
# VALIDATE_EVERY_STEP = 200
# SAVE_MODEL_EVERY_STEP = 8000
OUTPUT_DIR = "outputs"
